### ISSUE TITLE
12. Add roles administrator, user

### ISSUE THREAD

**Issue by 17felix** [17felix/Quake#13]
12. Add roles administrator, user. Configure a mechanism for restricting access to the API on the server side (authorization mechanism). To access the creation of a game session, connect and disconnect from a game session, view users participating in the current game session and to delete your account, there must be a user role.

### TODO
- [ ] add Admin
- [ ] add User
- [ ] add Authorization mechanism
   - [ ] access the creation of a game session
   - [ ] connect and disconnect from a game session
   - [ ] view users participating in the current game session
   - [ ] delete your account
