### ISSUE TITLE
14. Add Unit tests

### ISSUE THREAD

**Issue by 17felix** [17felix/Quake#15]
14. Cover the server part with unit tests, which is responsible for managing the game session by the user (viewing, creating, connecting, disconnecting from the game session). To write tests, use the **xUnit framework**.

### TODO
- [ ] unit test for Viewing
- [ ] unit test for creating
- [ ] unit test for Connecting
- [ ] unit test for Disconnecting
