### ISSUE TITLE
16. Add work with files to the application

### ISSUE THREAD

**Issue by 17felix** [17felix/Quake#17]
16. Add work with files to the application. Location files must be stored in a folder on the server, but at the same time there must be a record of their location in the database (link). For a location, both a poster for display and a typed file of the location itself must be stored.

### TODO 
- [ ] move `Location files` -> `server_folder`
- [ ] add Link of the  `Location files`  location in the database
- [ ] store Location poster
- [ ] store Location typed file
